### ISSUE TITLE
What Media Size for DVD Printing in Linux Driver? Canon iP7250

### ISSUE THREAD

**Issue by kszere** [centic9/glabels-ppa#1]
As in title.
I have Canon iP7250.
I select this param for printing DVD. Not tested yet.
![image](https://user-images.githubusercontent.com/7155051/38961793-80554c5a-436a-11e8-98db-edd2f273fac0.png)

**Comment by centic9** [comment]
Not sure how that relates to glabels, furthermore this repo is just about packaging glabels for Ubuntu, so I think you will need to discuss this elsewhere.
